[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM3
board_build.filesystem = littlefs

lib_deps =
  milesburton/DallasTemperature
  paulstoffregen/OneWire
  4-20ma/ModbusMaster
  bblanchon/ArduinoJson@^7.0.4

